### ISSUE TITLE
Band frequencies are still WSPR ones.

### ISSUE THREAD

**Issue by mkarliner** [Guenael/rtlsdr-ft8d#28]
title says it all.

**Comment by Guenael** [comment]
Yep, thanks for this notif!
I will update that too (an easy one!) :)

**Comment by Guenael** [comment]
Completed in this MR : https://github.com/Guenael/rtlsdr-ft8d/pull/33

But I don't want to deal with all different combination Region1/Region2...

Thanks for this ticket!
