### ISSUE TITLE
This does not work AT ALL

### ISSUE THREAD

**Issue by DE8MSH** [Guenael/rtlsdr-ft8d#48]
Hi.

Other RTLSDR tools working flawlesly. This tool does not work at all! I never got any decoding. Even if FT8 Signal is 1dB SNR. I tried all gain levels. I have RTLSDR V3. That RTL is purrfect in sense of stability.

**Comment by Guenael** [comment]
And this is not a bug report... 
No information about your OS, dongle hardware, version tested, frequency used, gain, etc..
What I'm supposed to do with this?
