### ISSUE TITLE
Chore: Finish PSK reporting :-)

### ISSUE THREAD

**Issue by mkarliner** [Guenael/rtlsdr-ft8d#49]
Working nicely now after latest merge.
Any chance of an early Christmas present?
Very grateful for all your efforts.

**Comment by Guenael** [comment]
Thanks for your feedback!
PSKreporter use IPFIX protocol, and forging your packets in C is painful... I guess I made a mistake in my packet stack and my packets just got rejected.
But you have a good idea, I will ask and IPFIX for Christmas ;)

**Comment by kholia** [comment]
In my projects, I have been using the following code for `spotting`.

https://github.com/drowe67/freedv-gui/blob/master/src/pskreporter.cpp

It works pretty well and is easy to compile and use.

**Comment by Guenael** [comment]
@kholia I will take a look, thanks!
I had other examples (in C++, but I have a requirement with C), it's pretty simple but I think I introduced a bug while forging the packet.

BTW, about FeedDV, you should put an explanation of what it does on the top of your GitHub page. It's very clear on the website (https://freedv.org/), but not on GitHub (more focused on how to build it, but when you discover this project, a general explanation is useful).

**Comment by Guenael** [comment]
BTW, I planned to only report CQ msg.
It's the default behavior, but should we report any callsign spotted?

**Comment by kholia** [comment]
Yes, any spotted callsigns should be reported (uploaded online) I think.

I am not a FreeDV developer, I just use their spotting code in my projects.

**Comment by mkarliner** [comment]
I would think that all spotted callsigns should be reported or have a command line switch.
I think WSJTX has the option so people can contest with no clutter on the screen , which isn't relavant 
in this case.

**Comment by Guenael** [comment]
I had some success reports on PSKreporter, but I guess it throttle my uploads/tests.
You should be able to upload some spots, but I need to write more code to deal with batch uploads.

**Comment by Guenael** [comment]
PSKreporter function disabled for now
