### ISSUE TITLE
40M band frequencies wrong

### ISSUE THREAD

**Issue by mkarliner** [Guenael/rtlsdr-ft8d#50]
./rtlsdr_ft8d  -d 2 -f 7m -c G8LKD -l IO91VN
Found 1 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00000001

Using device 0: Generic RTL2832U OEM
Found Rafael Micro R820T tuner
Enabled direct sampling mode, input 2

Starting rtlsdr-ft8d (2021-12-19, 11:06z) -- Version 0.3.3
  Callsign     : G8LKD
  Locator      : IO91VN
  Dial freq.   : 7000000 Hz
  Real freq.   : 7000000 Hz
  PPM factor   : 0
  Gain         : 29 dB
Wait for time sync (start in 8 sec)

I think there are others to check...

**Comment by Guenael** [comment]
@mkarliner Good catch!
All the frequencies are wrong, I fixed these frequencies previously, and I guess I override this part during a sync with `rtlsdr-wsprd`.
I will fix this, thanks!

**Comment by Guenael** [comment]
@mkarliner Frequencies fixed.
I also re-added the 1500 Hz offset. Using IQ sampling at 3200sps, it should give you -1600 & +1600Hz around this *real* dial frequency.
The back-end don't take this into account, so keep this in mind.
But for now, automated reporting is not available, so no big deal for now.

Thanks for opening this issue.
Fixed, but let me know if it's looks good to you.

73

**Comment by Guenael** [comment]
Frequencies fixed.
Thanks for reporting this issue!
