### ISSUE TITLE
No decodes with this program

### ISSUE THREAD

**Issue by kholia** [Guenael/rtlsdr-ft8d#67]
With this program:

```
$ ./rtlsdr_ft8d -a -f 20m -c VU3CER -l MK68
Found 1 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00000001

Using device 0: Generic RTL2832U OEM
Detached kernel driver
Found Rafael Micro R820T tuner
Enabled direct sampling mode, input 2

Starting rtlsdr-ft8d (2022-01-21, 15:07z) -- Version 0.3.6
  Callsign     : VU3CER
  Locator      : MK68
  Dial freq.   : 14074000 Hz
  Real freq.   : 14074000 Hz
  PPM factor   : 0
  Auto gain    : enable
Wait for time sync (start in 12 sec)

Allocating 15 zero-copy buffers
No spot 2022-01-21 15:07z
No spot 2022-01-21 15:08z
No spot 2022-01-21 15:08z
No spot 2022-01-21 15:08z
```

I have not been able to decode any FT8 traffic with this program.

With Gqrx + WSJT-X things are fine:

![Screenshot_2022-01-21_20-40-17](https://user-images.githubusercontent.com/79528/150550945-4b0910b3-f7ca-413d-81c7-f8d2ccc31a50.png)

The FT8 beacon is generated using https://github.com/kholia/Easy-Digital-Beacons-v1 project.

I am running Ubuntu 21.10 here.

```
$ ldd rtlsdr_ft8d
	linux-vdso.so.1 (0x00007ffc897f8000)
	libusb-1.0.so.0 => /lib/x86_64-linux-gnu/libusb-1.0.so.0 (0x00007fb29ec31000)
	librtlsdr.so.0 => /lib/x86_64-linux-gnu/librtlsdr.so.0 (0x00007fb29ec20000)

$ dpkg -S /lib/x86_64-linux-gnu/librtlsdr.so.0
dpkg-query: no path found matching pattern /lib/x86_64-linux-gnu/librtlsdr.so.0  # OK, we are not using the system packaged version
```

I am using the RTL-SDR Blog V.3. dongle here.

What could I do to debug this problem? Thank you for your time, and help.

Updates:

```
$ ./rtlsdr_ft8d -t -f 20m -c VU3CER -l MK68            
  Score     Freq       Call    Loc
     34 14074028       K1JT   FN20
Self-test SUCCESS!
```

The self-test works fine.

**Comment by kahara** [comment]
Same results here, tried with different gain settings but nothing gets decoded. Self-test ok.

**Comment by kahara** [comment]
A retraction, now was able to get some decodes out! Have to do more testing during next weekend.

**Comment by Guenael** [comment]
Glad to hear it!!
I guess you are using the HF band and not the VHF. I never tested the HF.
You might have an offset, feel free to share your settings or take a capture an check the spectrum with your preferred tool.
