### ISSUE TITLE
Impossible to install: Impossible Cloning

### ISSUE THREAD

**Issue by fg8oj** [Guenael/rtlsdr-ft8d#69]
Hi, I have this issue when I trying to install:

Clonage dans '/home/***/rtlsdr-ft8d/ft8_lib'...
fatal: impossible de se connecter à github.com :
github.com[0: 140.82.114.4]: errno=Connexion terminée par expiration du délai d'attente

fatal: le clonage de 'git://github.com/kgoba/ft8_lib' dans le chemin de sous-module '/home/fg8oj/rtlsdr-ft8d/ft8_lib' a échoué

Do you have any idea to solve this?
73, Burt FG8OJ

**Comment by fg8oj** [comment]
When I am using podman, the software is starting but I can't decode anything will I can decode it on wsjtx via my IC-9700 (I am using RadioAnalog panadapter IF output where I can see FT8 signal on GQRX.

podman run --rm -it --pull=always --device=/dev/bus/usb ghcr.io/guenael/rtlsdr-ft8d:latest -f 10m -c FG8OJ -l FK96hg -g 29
Trying to pull ghcr.io/guenael/rtlsdr-ft8d:latest...
Getting image source signatures
Copying blob f79ab0d8e58c skipped: already exists  
Copying blob f7a4b45093c1 skipped: already exists  
Copying blob 821f031e9f0f skipped: already exists  
Copying blob a2abf6c4d29d skipped: already exists  
Copying blob 569fe4e20b67 skipped: already exists  
Copying config 96495194f0 done  
Writing manifest to image destination
Storing signatures
Found 1 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00000001

Using device 0: Generic RTL2832U OEM
Found Rafael Micro R820T tuner
Enabled direct sampling mode, input 2

Starting rtlsdr-ft8d (2023-12-25, 02:00z) -- Version 0.3.6
  Callsign     : FG8OJ
  Locator      : FK96hg
  Dial freq.   : 28074000 Hz
  Real freq.   : 28074000 Hz
  PPM factor   : 0
  Gain         : 29 dB
Wait for time sync (start in 7 sec)

No spot 2023-12-25 02:00z
No spot 2023-12-25 02:00z
No spot 2023-12-25 02:01z
No spot 2023-12-25 02:01z
No spot 2023-12-25 02:01z
No spot 2023-12-25 02:01z
No spot 2023-12-25 02:02z
No spot 2023-12-25 02:02z
No spot 2023-12-25 02:02z
No spot 2023-12-25 02:02z

**Comment by fg8oj** [comment]
RTL USB Nooelec NESDR SMArTee v2 SDR
OS: Ubuntu 22.04
Self-test is working. 
podman run --rm -it --pull=always --device=/dev/bus/usb/001/010 ghcr.io/guenael/rtlsdr-ft8d:latest -f 10m -c FG8OJ -l FK96hg -a -d1 -t
Trying to pull ghcr.io/guenael/rtlsdr-ft8d:latest...
Getting image source signatures
Copying blob 821f031e9f0f skipped: already exists  
Copying blob 569fe4e20b67 skipped: already exists  
Copying blob a2abf6c4d29d skipped: already exists  
Copying blob f79ab0d8e58c skipped: already exists  
Copying blob f7a4b45093c1 skipped: already exists  
Copying config 96495194f0 done  
Writing manifest to image destination
Storing signatures
  Score     Freq       Call    Loc
     34 28074028       K1JT   FN20
Self-test SUCCESS!

**Comment by Guenael** [comment]
Hi Bertrand,
I guess you solved your installation / gitlab issue by yourself, good!!
About the decoding, make some recording (with gqrx) first, to make sure that a signal is visible on the waterfall, it's a good first step to troubleshoot your RX issue.
Having said that, RTL devices are not great for HF... This daemon was designed with VHF/UHF frequencies in mind first.
73, Guenael
