### ISSUE TITLE
minor changes

### ISSUE THREAD

**Issue by jonsnow1357** [Guenael/rtlsdr-ft8d#70]
Hi,

Some minor change requests ...

 * drop clang from Makefile, it seems to work fine with gcc. The user can specify the compiler using CLI.
 * change submodule path to https. This allows compiling without needing to auth with github.
 * some typo fixes in the help part

Please see attached for the diff file.
[rtlsdr-ft8d.diff.txt](https://github.com/Guenael/rtlsdr-ft8d/files/14188106/rtlsdr-ft8d.diff.txt)

Thank you

**Comment by Guenael** [comment]
Hi @jonsnow1357,
Thanks for the typo report and the http submodule recommendation, good idea.
About CLang vs GCC, yep it works fine with both, but at some point you have to pick one. And this time I chose CLang :) Any yep users can select another compiler, and I will mention this in the documentation.
73, Guenael
